//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AITLibrary.UserManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WUserDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WUserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int UserLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((this.UserLevelField.Equals(value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementService.UserManagementServiceSoap")]
    public interface UserManagementServiceSoap {
        
        // CODEGEN: Generating message contract since element name uid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateUser", ReplyAction="*")]
        AITLibrary.UserManagementService.validateUserResponse validateUser(AITLibrary.UserManagementService.validateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.validateUserResponse> validateUserAsync(AITLibrary.UserManagementService.validateUserRequest request);
        
        // CODEGEN: Generating message contract since element name RetrieveAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveAllUsers", ReplyAction="*")]
        AITLibrary.UserManagementService.RetrieveAllUsersResponse RetrieveAllUsers(AITLibrary.UserManagementService.RetrieveAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.RetrieveAllUsersResponse> RetrieveAllUsersAsync(AITLibrary.UserManagementService.RetrieveAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        AITLibrary.UserManagementService.AddUserResponse AddUser(AITLibrary.UserManagementService.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.AddUserResponse> AddUserAsync(AITLibrary.UserManagementService.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        AITLibrary.UserManagementService.UpdateUserResponse UpdateUser(AITLibrary.UserManagementService.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.UpdateUserResponse> UpdateUserAsync(AITLibrary.UserManagementService.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        int DeleteUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(int userID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUser", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.validateUserRequestBody Body;
        
        public validateUserRequest() {
        }
        
        public validateUserRequest(AITLibrary.UserManagementService.validateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pw;
        
        public validateUserRequestBody() {
        }
        
        public validateUserRequestBody(string uid, string pw) {
            this.uid = uid;
            this.pw = pw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.validateUserResponseBody Body;
        
        public validateUserResponse() {
        }
        
        public validateUserResponse(AITLibrary.UserManagementService.validateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.UserManagementService.WUserDTO validateUserResult;
        
        public validateUserResponseBody() {
        }
        
        public validateUserResponseBody(AITLibrary.UserManagementService.WUserDTO validateUserResult) {
            this.validateUserResult = validateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.RetrieveAllUsersRequestBody Body;
        
        public RetrieveAllUsersRequest() {
        }
        
        public RetrieveAllUsersRequest(AITLibrary.UserManagementService.RetrieveAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetrieveAllUsersRequestBody {
        
        public RetrieveAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.RetrieveAllUsersResponseBody Body;
        
        public RetrieveAllUsersResponse() {
        }
        
        public RetrieveAllUsersResponse(AITLibrary.UserManagementService.RetrieveAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.UserManagementService.WUserDTO[] RetrieveAllUsersResult;
        
        public RetrieveAllUsersResponseBody() {
        }
        
        public RetrieveAllUsersResponseBody(AITLibrary.UserManagementService.WUserDTO[] RetrieveAllUsersResult) {
            this.RetrieveAllUsersResult = RetrieveAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(AITLibrary.UserManagementService.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.UserManagementService.WUserDTO user;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(AITLibrary.UserManagementService.WUserDTO user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(AITLibrary.UserManagementService.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(int AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(AITLibrary.UserManagementService.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.UserManagementService.WUserDTO user;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(AITLibrary.UserManagementService.WUserDTO user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.UserManagementService.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(AITLibrary.UserManagementService.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(int UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserManagementServiceSoapChannel : AITLibrary.UserManagementService.UserManagementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementServiceSoapClient : System.ServiceModel.ClientBase<AITLibrary.UserManagementService.UserManagementServiceSoap>, AITLibrary.UserManagementService.UserManagementServiceSoap {
        
        public UserManagementServiceSoapClient() {
        }
        
        public UserManagementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.UserManagementService.validateUserResponse AITLibrary.UserManagementService.UserManagementServiceSoap.validateUser(AITLibrary.UserManagementService.validateUserRequest request) {
            return base.Channel.validateUser(request);
        }
        
        public AITLibrary.UserManagementService.WUserDTO validateUser(string uid, string pw) {
            AITLibrary.UserManagementService.validateUserRequest inValue = new AITLibrary.UserManagementService.validateUserRequest();
            inValue.Body = new AITLibrary.UserManagementService.validateUserRequestBody();
            inValue.Body.uid = uid;
            inValue.Body.pw = pw;
            AITLibrary.UserManagementService.validateUserResponse retVal = ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).validateUser(inValue);
            return retVal.Body.validateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.validateUserResponse> AITLibrary.UserManagementService.UserManagementServiceSoap.validateUserAsync(AITLibrary.UserManagementService.validateUserRequest request) {
            return base.Channel.validateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.UserManagementService.validateUserResponse> validateUserAsync(string uid, string pw) {
            AITLibrary.UserManagementService.validateUserRequest inValue = new AITLibrary.UserManagementService.validateUserRequest();
            inValue.Body = new AITLibrary.UserManagementService.validateUserRequestBody();
            inValue.Body.uid = uid;
            inValue.Body.pw = pw;
            return ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).validateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.UserManagementService.RetrieveAllUsersResponse AITLibrary.UserManagementService.UserManagementServiceSoap.RetrieveAllUsers(AITLibrary.UserManagementService.RetrieveAllUsersRequest request) {
            return base.Channel.RetrieveAllUsers(request);
        }
        
        public AITLibrary.UserManagementService.WUserDTO[] RetrieveAllUsers() {
            AITLibrary.UserManagementService.RetrieveAllUsersRequest inValue = new AITLibrary.UserManagementService.RetrieveAllUsersRequest();
            inValue.Body = new AITLibrary.UserManagementService.RetrieveAllUsersRequestBody();
            AITLibrary.UserManagementService.RetrieveAllUsersResponse retVal = ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).RetrieveAllUsers(inValue);
            return retVal.Body.RetrieveAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.RetrieveAllUsersResponse> AITLibrary.UserManagementService.UserManagementServiceSoap.RetrieveAllUsersAsync(AITLibrary.UserManagementService.RetrieveAllUsersRequest request) {
            return base.Channel.RetrieveAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.UserManagementService.RetrieveAllUsersResponse> RetrieveAllUsersAsync() {
            AITLibrary.UserManagementService.RetrieveAllUsersRequest inValue = new AITLibrary.UserManagementService.RetrieveAllUsersRequest();
            inValue.Body = new AITLibrary.UserManagementService.RetrieveAllUsersRequestBody();
            return ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).RetrieveAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.UserManagementService.AddUserResponse AITLibrary.UserManagementService.UserManagementServiceSoap.AddUser(AITLibrary.UserManagementService.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public int AddUser(AITLibrary.UserManagementService.WUserDTO user) {
            AITLibrary.UserManagementService.AddUserRequest inValue = new AITLibrary.UserManagementService.AddUserRequest();
            inValue.Body = new AITLibrary.UserManagementService.AddUserRequestBody();
            inValue.Body.user = user;
            AITLibrary.UserManagementService.AddUserResponse retVal = ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.AddUserResponse> AITLibrary.UserManagementService.UserManagementServiceSoap.AddUserAsync(AITLibrary.UserManagementService.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.UserManagementService.AddUserResponse> AddUserAsync(AITLibrary.UserManagementService.WUserDTO user) {
            AITLibrary.UserManagementService.AddUserRequest inValue = new AITLibrary.UserManagementService.AddUserRequest();
            inValue.Body = new AITLibrary.UserManagementService.AddUserRequestBody();
            inValue.Body.user = user;
            return ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.UserManagementService.UpdateUserResponse AITLibrary.UserManagementService.UserManagementServiceSoap.UpdateUser(AITLibrary.UserManagementService.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public int UpdateUser(AITLibrary.UserManagementService.WUserDTO user) {
            AITLibrary.UserManagementService.UpdateUserRequest inValue = new AITLibrary.UserManagementService.UpdateUserRequest();
            inValue.Body = new AITLibrary.UserManagementService.UpdateUserRequestBody();
            inValue.Body.user = user;
            AITLibrary.UserManagementService.UpdateUserResponse retVal = ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.UserManagementService.UpdateUserResponse> AITLibrary.UserManagementService.UserManagementServiceSoap.UpdateUserAsync(AITLibrary.UserManagementService.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.UserManagementService.UpdateUserResponse> UpdateUserAsync(AITLibrary.UserManagementService.WUserDTO user) {
            AITLibrary.UserManagementService.UpdateUserRequest inValue = new AITLibrary.UserManagementService.UpdateUserRequest();
            inValue.Body = new AITLibrary.UserManagementService.UpdateUserRequestBody();
            inValue.Body.user = user;
            return ((AITLibrary.UserManagementService.UserManagementServiceSoap)(this)).UpdateUserAsync(inValue);
        }
        
        public int DeleteUser(int userID) {
            return base.Channel.DeleteUser(userID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(int userID) {
            return base.Channel.DeleteUserAsync(userID);
        }
    }
}
