//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AITLibrary.MediaManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WMediaDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WMediaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int mediaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mediaTitleField;
        
        private int genreField;
        
        private int directorField;
        
        private int languageField;
        
        private int publishYearField;
        
        private decimal budgetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int mediaID {
            get {
                return this.mediaIDField;
            }
            set {
                if ((this.mediaIDField.Equals(value) != true)) {
                    this.mediaIDField = value;
                    this.RaisePropertyChanged("mediaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mediaTitle {
            get {
                return this.mediaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.mediaTitleField, value) != true)) {
                    this.mediaTitleField = value;
                    this.RaisePropertyChanged("mediaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int genre {
            get {
                return this.genreField;
            }
            set {
                if ((this.genreField.Equals(value) != true)) {
                    this.genreField = value;
                    this.RaisePropertyChanged("genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int director {
            get {
                return this.directorField;
            }
            set {
                if ((this.directorField.Equals(value) != true)) {
                    this.directorField = value;
                    this.RaisePropertyChanged("director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int language {
            get {
                return this.languageField;
            }
            set {
                if ((this.languageField.Equals(value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int publishYear {
            get {
                return this.publishYearField;
            }
            set {
                if ((this.publishYearField.Equals(value) != true)) {
                    this.publishYearField = value;
                    this.RaisePropertyChanged("publishYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal budget {
            get {
                return this.budgetField;
            }
            set {
                if ((this.budgetField.Equals(value) != true)) {
                    this.budgetField = value;
                    this.RaisePropertyChanged("budget");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WBorrowDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WBorrowDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BIDField;
        
        private int UIDField;
        
        private int MediaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MediaTitleField;
        
        private System.DateTime BorrowDateField;
        
        private System.DateTime ReturnDateField;
        
        private System.DateTime ActualReturnDateField;
        
        private decimal LateFeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BID {
            get {
                return this.BIDField;
            }
            set {
                if ((this.BIDField.Equals(value) != true)) {
                    this.BIDField = value;
                    this.RaisePropertyChanged("BID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int MediaID {
            get {
                return this.MediaIDField;
            }
            set {
                if ((this.MediaIDField.Equals(value) != true)) {
                    this.MediaIDField = value;
                    this.RaisePropertyChanged("MediaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MediaTitle {
            get {
                return this.MediaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaTitleField, value) != true)) {
                    this.MediaTitleField = value;
                    this.RaisePropertyChanged("MediaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime BorrowDate {
            get {
                return this.BorrowDateField;
            }
            set {
                if ((this.BorrowDateField.Equals(value) != true)) {
                    this.BorrowDateField = value;
                    this.RaisePropertyChanged("BorrowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime ActualReturnDate {
            get {
                return this.ActualReturnDateField;
            }
            set {
                if ((this.ActualReturnDateField.Equals(value) != true)) {
                    this.ActualReturnDateField = value;
                    this.RaisePropertyChanged("ActualReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal LateFee {
            get {
                return this.LateFeeField;
            }
            set {
                if ((this.LateFeeField.Equals(value) != true)) {
                    this.LateFeeField = value;
                    this.RaisePropertyChanged("LateFee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WReservationsDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WReservationsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        private int RIDField;
        
        private int UIDField;
        
        private int MediaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MediaTitleField;
        
        private System.DateTime ReservedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int RID {
            get {
                return this.RIDField;
            }
            set {
                if ((this.RIDField.Equals(value) != true)) {
                    this.RIDField = value;
                    this.RaisePropertyChanged("RID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MediaID {
            get {
                return this.MediaIDField;
            }
            set {
                if ((this.MediaIDField.Equals(value) != true)) {
                    this.MediaIDField = value;
                    this.RaisePropertyChanged("MediaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MediaTitle {
            get {
                return this.MediaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaTitleField, value) != true)) {
                    this.MediaTitleField = value;
                    this.RaisePropertyChanged("MediaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime ReservedDate {
            get {
                return this.ReservedDateField;
            }
            set {
                if ((this.ReservedDateField.Equals(value) != true)) {
                    this.ReservedDateField = value;
                    this.RaisePropertyChanged("ReservedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MediaManagementService.MediaManagementServiceSoap")]
    public interface MediaManagementServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllMediaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMedia", ReplyAction="*")]
        AITLibrary.MediaManagementService.GetAllMediaResponse GetAllMedia(AITLibrary.MediaManagementService.GetAllMediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.GetAllMediaResponse> GetAllMediaAsync(AITLibrary.MediaManagementService.GetAllMediaRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeySearch", ReplyAction="*")]
        AITLibrary.MediaManagementService.KeySearchResponse KeySearch(AITLibrary.MediaManagementService.KeySearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeySearch", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.KeySearchResponse> KeySearchAsync(AITLibrary.MediaManagementService.KeySearchRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdSearch", ReplyAction="*")]
        AITLibrary.MediaManagementService.IdSearchResponse IdSearch(AITLibrary.MediaManagementService.IdSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.IdSearchResponse> IdSearchAsync(AITLibrary.MediaManagementService.IdSearchRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TitleSearch", ReplyAction="*")]
        AITLibrary.MediaManagementService.TitleSearchResponse TitleSearch(AITLibrary.MediaManagementService.TitleSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TitleSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.TitleSearchResponse> TitleSearchAsync(AITLibrary.MediaManagementService.TitleSearchRequest request);
        
        // CODEGEN: Generating message contract since element name RetrieveMediaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveMedia", ReplyAction="*")]
        AITLibrary.MediaManagementService.RetrieveMediaResponse RetrieveMedia(AITLibrary.MediaManagementService.RetrieveMediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.RetrieveMediaResponse> RetrieveMediaAsync(AITLibrary.MediaManagementService.RetrieveMediaRequest request);
        
        // CODEGEN: Generating message contract since element name MyBorrowListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyBorrowList", ReplyAction="*")]
        AITLibrary.MediaManagementService.MyBorrowListResponse MyBorrowList(AITLibrary.MediaManagementService.MyBorrowListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyBorrowList", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.MyBorrowListResponse> MyBorrowListAsync(AITLibrary.MediaManagementService.MyBorrowListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowMedia", ReplyAction="*")]
        int BorrowMedia(int userID, int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BorrowMediaAsync(int userID, int mediaID);
        
        // CODEGEN: Generating message contract since element name MyReservationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyReservations", ReplyAction="*")]
        AITLibrary.MediaManagementService.MyReservationsResponse MyReservations(AITLibrary.MediaManagementService.MyReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MyReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.MyReservationsResponse> MyReservationsAsync(AITLibrary.MediaManagementService.MyReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveMedia", ReplyAction="*")]
        int ReserveMedia(int userID, int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ReserveMediaAsync(int userID, int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelReservation", ReplyAction="*")]
        void CancelReservation(int userID, int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelReservation", ReplyAction="*")]
        System.Threading.Tasks.Task CancelReservationAsync(int userID, int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMedia", ReplyAction="*")]
        bool DeleteMedia(int mediaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteMediaAsync(int mediaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnMedia", ReplyAction="*")]
        bool ReturnMedia(int userID, int mediaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ReturnMediaAsync(int userID, int mediaID);
        
        // CODEGEN: Generating message contract since element name media from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMedia", ReplyAction="*")]
        AITLibrary.MediaManagementService.InsertMediaResponse InsertMedia(AITLibrary.MediaManagementService.InsertMediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.InsertMediaResponse> InsertMediaAsync(AITLibrary.MediaManagementService.InsertMediaRequest request);
        
        // CODEGEN: Generating message contract since element name media from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMedia", ReplyAction="*")]
        AITLibrary.MediaManagementService.UpdateMediaResponse UpdateMedia(AITLibrary.MediaManagementService.UpdateMediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMedia", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.UpdateMediaResponse> UpdateMediaAsync(AITLibrary.MediaManagementService.UpdateMediaRequest request);
        
        // CODEGEN: Generating message contract since element name BorrowListsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowLists", ReplyAction="*")]
        AITLibrary.MediaManagementService.BorrowListsResponse BorrowLists(AITLibrary.MediaManagementService.BorrowListsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowLists", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.BorrowListsResponse> BorrowListsAsync(AITLibrary.MediaManagementService.BorrowListsRequest request);
        
        // CODEGEN: Generating message contract since element name ReserveListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveList", ReplyAction="*")]
        AITLibrary.MediaManagementService.ReserveListResponse ReserveList(AITLibrary.MediaManagementService.ReserveListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveList", ReplyAction="*")]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.ReserveListResponse> ReserveListAsync(AITLibrary.MediaManagementService.ReserveListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMedia", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.GetAllMediaRequestBody Body;
        
        public GetAllMediaRequest() {
        }
        
        public GetAllMediaRequest(AITLibrary.MediaManagementService.GetAllMediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMediaRequestBody {
        
        public GetAllMediaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.GetAllMediaResponseBody Body;
        
        public GetAllMediaResponse() {
        }
        
        public GetAllMediaResponse(AITLibrary.MediaManagementService.GetAllMediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WMediaDTO[] GetAllMediaResult;
        
        public GetAllMediaResponseBody() {
        }
        
        public GetAllMediaResponseBody(AITLibrary.MediaManagementService.WMediaDTO[] GetAllMediaResult) {
            this.GetAllMediaResult = GetAllMediaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeySearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeySearch", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.KeySearchRequestBody Body;
        
        public KeySearchRequest() {
        }
        
        public KeySearchRequest(AITLibrary.MediaManagementService.KeySearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeySearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        public KeySearchRequestBody() {
        }
        
        public KeySearchRequestBody(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeySearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeySearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.KeySearchResponseBody Body;
        
        public KeySearchResponse() {
        }
        
        public KeySearchResponse(AITLibrary.MediaManagementService.KeySearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeySearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WMediaDTO[] KeySearchResult;
        
        public KeySearchResponseBody() {
        }
        
        public KeySearchResponseBody(AITLibrary.MediaManagementService.WMediaDTO[] KeySearchResult) {
            this.KeySearchResult = KeySearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdSearch", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.IdSearchRequestBody Body;
        
        public IdSearchRequest() {
        }
        
        public IdSearchRequest(AITLibrary.MediaManagementService.IdSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IdSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public IdSearchRequestBody() {
        }
        
        public IdSearchRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdSearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.IdSearchResponseBody Body;
        
        public IdSearchResponse() {
        }
        
        public IdSearchResponse(AITLibrary.MediaManagementService.IdSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IdSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WMediaDTO[] IdSearchResult;
        
        public IdSearchResponseBody() {
        }
        
        public IdSearchResponseBody(AITLibrary.MediaManagementService.WMediaDTO[] IdSearchResult) {
            this.IdSearchResult = IdSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleSearch", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.TitleSearchRequestBody Body;
        
        public TitleSearchRequest() {
        }
        
        public TitleSearchRequest(AITLibrary.MediaManagementService.TitleSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TitleSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public TitleSearchRequestBody() {
        }
        
        public TitleSearchRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleSearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.TitleSearchResponseBody Body;
        
        public TitleSearchResponse() {
        }
        
        public TitleSearchResponse(AITLibrary.MediaManagementService.TitleSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TitleSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WMediaDTO[] TitleSearchResult;
        
        public TitleSearchResponseBody() {
        }
        
        public TitleSearchResponseBody(AITLibrary.MediaManagementService.WMediaDTO[] TitleSearchResult) {
            this.TitleSearchResult = TitleSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveMediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveMedia", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.RetrieveMediaRequestBody Body;
        
        public RetrieveMediaRequest() {
        }
        
        public RetrieveMediaRequest(AITLibrary.MediaManagementService.RetrieveMediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveMediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mediaID;
        
        public RetrieveMediaRequestBody() {
        }
        
        public RetrieveMediaRequestBody(int mediaID) {
            this.mediaID = mediaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveMediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveMediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.RetrieveMediaResponseBody Body;
        
        public RetrieveMediaResponse() {
        }
        
        public RetrieveMediaResponse(AITLibrary.MediaManagementService.RetrieveMediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveMediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WMediaDTO RetrieveMediaResult;
        
        public RetrieveMediaResponseBody() {
        }
        
        public RetrieveMediaResponseBody(AITLibrary.MediaManagementService.WMediaDTO RetrieveMediaResult) {
            this.RetrieveMediaResult = RetrieveMediaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyBorrowListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyBorrowList", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.MyBorrowListRequestBody Body;
        
        public MyBorrowListRequest() {
        }
        
        public MyBorrowListRequest(AITLibrary.MediaManagementService.MyBorrowListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MyBorrowListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        public MyBorrowListRequestBody() {
        }
        
        public MyBorrowListRequestBody(int userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyBorrowListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyBorrowListResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.MyBorrowListResponseBody Body;
        
        public MyBorrowListResponse() {
        }
        
        public MyBorrowListResponse(AITLibrary.MediaManagementService.MyBorrowListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MyBorrowListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WBorrowDTO[] MyBorrowListResult;
        
        public MyBorrowListResponseBody() {
        }
        
        public MyBorrowListResponseBody(AITLibrary.MediaManagementService.WBorrowDTO[] MyBorrowListResult) {
            this.MyBorrowListResult = MyBorrowListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyReservations", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.MyReservationsRequestBody Body;
        
        public MyReservationsRequest() {
        }
        
        public MyReservationsRequest(AITLibrary.MediaManagementService.MyReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MyReservationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        public MyReservationsRequestBody() {
        }
        
        public MyReservationsRequestBody(int userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MyReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MyReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.MyReservationsResponseBody Body;
        
        public MyReservationsResponse() {
        }
        
        public MyReservationsResponse(AITLibrary.MediaManagementService.MyReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MyReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WReservationsDTO[] MyReservationsResult;
        
        public MyReservationsResponseBody() {
        }
        
        public MyReservationsResponseBody(AITLibrary.MediaManagementService.WReservationsDTO[] MyReservationsResult) {
            this.MyReservationsResult = MyReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMedia", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.InsertMediaRequestBody Body;
        
        public InsertMediaRequest() {
        }
        
        public InsertMediaRequest(AITLibrary.MediaManagementService.InsertMediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WMediaDTO media;
        
        public InsertMediaRequestBody() {
        }
        
        public InsertMediaRequestBody(AITLibrary.MediaManagementService.WMediaDTO media) {
            this.media = media;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.InsertMediaResponseBody Body;
        
        public InsertMediaResponse() {
        }
        
        public InsertMediaResponse(AITLibrary.MediaManagementService.InsertMediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertMediaResult;
        
        public InsertMediaResponseBody() {
        }
        
        public InsertMediaResponseBody(bool InsertMediaResult) {
            this.InsertMediaResult = InsertMediaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMedia", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.UpdateMediaRequestBody Body;
        
        public UpdateMediaRequest() {
        }
        
        public UpdateMediaRequest(AITLibrary.MediaManagementService.UpdateMediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WMediaDTO media;
        
        public UpdateMediaRequestBody() {
        }
        
        public UpdateMediaRequestBody(AITLibrary.MediaManagementService.WMediaDTO media) {
            this.media = media;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.UpdateMediaResponseBody Body;
        
        public UpdateMediaResponse() {
        }
        
        public UpdateMediaResponse(AITLibrary.MediaManagementService.UpdateMediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateMediaResult;
        
        public UpdateMediaResponseBody() {
        }
        
        public UpdateMediaResponseBody(bool UpdateMediaResult) {
            this.UpdateMediaResult = UpdateMediaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrowListsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrowLists", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.BorrowListsRequestBody Body;
        
        public BorrowListsRequest() {
        }
        
        public BorrowListsRequest(AITLibrary.MediaManagementService.BorrowListsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BorrowListsRequestBody {
        
        public BorrowListsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrowListsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrowListsResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.BorrowListsResponseBody Body;
        
        public BorrowListsResponse() {
        }
        
        public BorrowListsResponse(AITLibrary.MediaManagementService.BorrowListsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrowListsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WBorrowDTO[] BorrowListsResult;
        
        public BorrowListsResponseBody() {
        }
        
        public BorrowListsResponseBody(AITLibrary.MediaManagementService.WBorrowDTO[] BorrowListsResult) {
            this.BorrowListsResult = BorrowListsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveList", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.ReserveListRequestBody Body;
        
        public ReserveListRequest() {
        }
        
        public ReserveListRequest(AITLibrary.MediaManagementService.ReserveListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReserveListRequestBody {
        
        public ReserveListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveListResponse", Namespace="http://tempuri.org/", Order=0)]
        public AITLibrary.MediaManagementService.ReserveListResponseBody Body;
        
        public ReserveListResponse() {
        }
        
        public ReserveListResponse(AITLibrary.MediaManagementService.ReserveListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AITLibrary.MediaManagementService.WReservationsDTO[] ReserveListResult;
        
        public ReserveListResponseBody() {
        }
        
        public ReserveListResponseBody(AITLibrary.MediaManagementService.WReservationsDTO[] ReserveListResult) {
            this.ReserveListResult = ReserveListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MediaManagementServiceSoapChannel : AITLibrary.MediaManagementService.MediaManagementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediaManagementServiceSoapClient : System.ServiceModel.ClientBase<AITLibrary.MediaManagementService.MediaManagementServiceSoap>, AITLibrary.MediaManagementService.MediaManagementServiceSoap {
        
        public MediaManagementServiceSoapClient() {
        }
        
        public MediaManagementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediaManagementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaManagementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaManagementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.GetAllMediaResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.GetAllMedia(AITLibrary.MediaManagementService.GetAllMediaRequest request) {
            return base.Channel.GetAllMedia(request);
        }
        
        public AITLibrary.MediaManagementService.WMediaDTO[] GetAllMedia() {
            AITLibrary.MediaManagementService.GetAllMediaRequest inValue = new AITLibrary.MediaManagementService.GetAllMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.GetAllMediaRequestBody();
            AITLibrary.MediaManagementService.GetAllMediaResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).GetAllMedia(inValue);
            return retVal.Body.GetAllMediaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.GetAllMediaResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.GetAllMediaAsync(AITLibrary.MediaManagementService.GetAllMediaRequest request) {
            return base.Channel.GetAllMediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.GetAllMediaResponse> GetAllMediaAsync() {
            AITLibrary.MediaManagementService.GetAllMediaRequest inValue = new AITLibrary.MediaManagementService.GetAllMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.GetAllMediaRequestBody();
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).GetAllMediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.KeySearchResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.KeySearch(AITLibrary.MediaManagementService.KeySearchRequest request) {
            return base.Channel.KeySearch(request);
        }
        
        public AITLibrary.MediaManagementService.WMediaDTO[] KeySearch(string search) {
            AITLibrary.MediaManagementService.KeySearchRequest inValue = new AITLibrary.MediaManagementService.KeySearchRequest();
            inValue.Body = new AITLibrary.MediaManagementService.KeySearchRequestBody();
            inValue.Body.search = search;
            AITLibrary.MediaManagementService.KeySearchResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).KeySearch(inValue);
            return retVal.Body.KeySearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.KeySearchResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.KeySearchAsync(AITLibrary.MediaManagementService.KeySearchRequest request) {
            return base.Channel.KeySearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.KeySearchResponse> KeySearchAsync(string search) {
            AITLibrary.MediaManagementService.KeySearchRequest inValue = new AITLibrary.MediaManagementService.KeySearchRequest();
            inValue.Body = new AITLibrary.MediaManagementService.KeySearchRequestBody();
            inValue.Body.search = search;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).KeySearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.IdSearchResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.IdSearch(AITLibrary.MediaManagementService.IdSearchRequest request) {
            return base.Channel.IdSearch(request);
        }
        
        public AITLibrary.MediaManagementService.WMediaDTO[] IdSearch(string id) {
            AITLibrary.MediaManagementService.IdSearchRequest inValue = new AITLibrary.MediaManagementService.IdSearchRequest();
            inValue.Body = new AITLibrary.MediaManagementService.IdSearchRequestBody();
            inValue.Body.id = id;
            AITLibrary.MediaManagementService.IdSearchResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).IdSearch(inValue);
            return retVal.Body.IdSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.IdSearchResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.IdSearchAsync(AITLibrary.MediaManagementService.IdSearchRequest request) {
            return base.Channel.IdSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.IdSearchResponse> IdSearchAsync(string id) {
            AITLibrary.MediaManagementService.IdSearchRequest inValue = new AITLibrary.MediaManagementService.IdSearchRequest();
            inValue.Body = new AITLibrary.MediaManagementService.IdSearchRequestBody();
            inValue.Body.id = id;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).IdSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.TitleSearchResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.TitleSearch(AITLibrary.MediaManagementService.TitleSearchRequest request) {
            return base.Channel.TitleSearch(request);
        }
        
        public AITLibrary.MediaManagementService.WMediaDTO[] TitleSearch(string title) {
            AITLibrary.MediaManagementService.TitleSearchRequest inValue = new AITLibrary.MediaManagementService.TitleSearchRequest();
            inValue.Body = new AITLibrary.MediaManagementService.TitleSearchRequestBody();
            inValue.Body.title = title;
            AITLibrary.MediaManagementService.TitleSearchResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).TitleSearch(inValue);
            return retVal.Body.TitleSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.TitleSearchResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.TitleSearchAsync(AITLibrary.MediaManagementService.TitleSearchRequest request) {
            return base.Channel.TitleSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.TitleSearchResponse> TitleSearchAsync(string title) {
            AITLibrary.MediaManagementService.TitleSearchRequest inValue = new AITLibrary.MediaManagementService.TitleSearchRequest();
            inValue.Body = new AITLibrary.MediaManagementService.TitleSearchRequestBody();
            inValue.Body.title = title;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).TitleSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.RetrieveMediaResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.RetrieveMedia(AITLibrary.MediaManagementService.RetrieveMediaRequest request) {
            return base.Channel.RetrieveMedia(request);
        }
        
        public AITLibrary.MediaManagementService.WMediaDTO RetrieveMedia(int mediaID) {
            AITLibrary.MediaManagementService.RetrieveMediaRequest inValue = new AITLibrary.MediaManagementService.RetrieveMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.RetrieveMediaRequestBody();
            inValue.Body.mediaID = mediaID;
            AITLibrary.MediaManagementService.RetrieveMediaResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).RetrieveMedia(inValue);
            return retVal.Body.RetrieveMediaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.RetrieveMediaResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.RetrieveMediaAsync(AITLibrary.MediaManagementService.RetrieveMediaRequest request) {
            return base.Channel.RetrieveMediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.RetrieveMediaResponse> RetrieveMediaAsync(int mediaID) {
            AITLibrary.MediaManagementService.RetrieveMediaRequest inValue = new AITLibrary.MediaManagementService.RetrieveMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.RetrieveMediaRequestBody();
            inValue.Body.mediaID = mediaID;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).RetrieveMediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.MyBorrowListResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.MyBorrowList(AITLibrary.MediaManagementService.MyBorrowListRequest request) {
            return base.Channel.MyBorrowList(request);
        }
        
        public AITLibrary.MediaManagementService.WBorrowDTO[] MyBorrowList(int userID) {
            AITLibrary.MediaManagementService.MyBorrowListRequest inValue = new AITLibrary.MediaManagementService.MyBorrowListRequest();
            inValue.Body = new AITLibrary.MediaManagementService.MyBorrowListRequestBody();
            inValue.Body.userID = userID;
            AITLibrary.MediaManagementService.MyBorrowListResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).MyBorrowList(inValue);
            return retVal.Body.MyBorrowListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.MyBorrowListResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.MyBorrowListAsync(AITLibrary.MediaManagementService.MyBorrowListRequest request) {
            return base.Channel.MyBorrowListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.MyBorrowListResponse> MyBorrowListAsync(int userID) {
            AITLibrary.MediaManagementService.MyBorrowListRequest inValue = new AITLibrary.MediaManagementService.MyBorrowListRequest();
            inValue.Body = new AITLibrary.MediaManagementService.MyBorrowListRequestBody();
            inValue.Body.userID = userID;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).MyBorrowListAsync(inValue);
        }
        
        public int BorrowMedia(int userID, int mediaID) {
            return base.Channel.BorrowMedia(userID, mediaID);
        }
        
        public System.Threading.Tasks.Task<int> BorrowMediaAsync(int userID, int mediaID) {
            return base.Channel.BorrowMediaAsync(userID, mediaID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.MyReservationsResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.MyReservations(AITLibrary.MediaManagementService.MyReservationsRequest request) {
            return base.Channel.MyReservations(request);
        }
        
        public AITLibrary.MediaManagementService.WReservationsDTO[] MyReservations(int userID) {
            AITLibrary.MediaManagementService.MyReservationsRequest inValue = new AITLibrary.MediaManagementService.MyReservationsRequest();
            inValue.Body = new AITLibrary.MediaManagementService.MyReservationsRequestBody();
            inValue.Body.userID = userID;
            AITLibrary.MediaManagementService.MyReservationsResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).MyReservations(inValue);
            return retVal.Body.MyReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.MyReservationsResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.MyReservationsAsync(AITLibrary.MediaManagementService.MyReservationsRequest request) {
            return base.Channel.MyReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.MyReservationsResponse> MyReservationsAsync(int userID) {
            AITLibrary.MediaManagementService.MyReservationsRequest inValue = new AITLibrary.MediaManagementService.MyReservationsRequest();
            inValue.Body = new AITLibrary.MediaManagementService.MyReservationsRequestBody();
            inValue.Body.userID = userID;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).MyReservationsAsync(inValue);
        }
        
        public int ReserveMedia(int userID, int mediaID) {
            return base.Channel.ReserveMedia(userID, mediaID);
        }
        
        public System.Threading.Tasks.Task<int> ReserveMediaAsync(int userID, int mediaID) {
            return base.Channel.ReserveMediaAsync(userID, mediaID);
        }
        
        public void CancelReservation(int userID, int mediaID) {
            base.Channel.CancelReservation(userID, mediaID);
        }
        
        public System.Threading.Tasks.Task CancelReservationAsync(int userID, int mediaID) {
            return base.Channel.CancelReservationAsync(userID, mediaID);
        }
        
        public bool DeleteMedia(int mediaId) {
            return base.Channel.DeleteMedia(mediaId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMediaAsync(int mediaId) {
            return base.Channel.DeleteMediaAsync(mediaId);
        }
        
        public bool ReturnMedia(int userID, int mediaID) {
            return base.Channel.ReturnMedia(userID, mediaID);
        }
        
        public System.Threading.Tasks.Task<bool> ReturnMediaAsync(int userID, int mediaID) {
            return base.Channel.ReturnMediaAsync(userID, mediaID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.InsertMediaResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.InsertMedia(AITLibrary.MediaManagementService.InsertMediaRequest request) {
            return base.Channel.InsertMedia(request);
        }
        
        public bool InsertMedia(AITLibrary.MediaManagementService.WMediaDTO media) {
            AITLibrary.MediaManagementService.InsertMediaRequest inValue = new AITLibrary.MediaManagementService.InsertMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.InsertMediaRequestBody();
            inValue.Body.media = media;
            AITLibrary.MediaManagementService.InsertMediaResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).InsertMedia(inValue);
            return retVal.Body.InsertMediaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.InsertMediaResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.InsertMediaAsync(AITLibrary.MediaManagementService.InsertMediaRequest request) {
            return base.Channel.InsertMediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.InsertMediaResponse> InsertMediaAsync(AITLibrary.MediaManagementService.WMediaDTO media) {
            AITLibrary.MediaManagementService.InsertMediaRequest inValue = new AITLibrary.MediaManagementService.InsertMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.InsertMediaRequestBody();
            inValue.Body.media = media;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).InsertMediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.UpdateMediaResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.UpdateMedia(AITLibrary.MediaManagementService.UpdateMediaRequest request) {
            return base.Channel.UpdateMedia(request);
        }
        
        public bool UpdateMedia(AITLibrary.MediaManagementService.WMediaDTO media) {
            AITLibrary.MediaManagementService.UpdateMediaRequest inValue = new AITLibrary.MediaManagementService.UpdateMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.UpdateMediaRequestBody();
            inValue.Body.media = media;
            AITLibrary.MediaManagementService.UpdateMediaResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).UpdateMedia(inValue);
            return retVal.Body.UpdateMediaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.UpdateMediaResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.UpdateMediaAsync(AITLibrary.MediaManagementService.UpdateMediaRequest request) {
            return base.Channel.UpdateMediaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.UpdateMediaResponse> UpdateMediaAsync(AITLibrary.MediaManagementService.WMediaDTO media) {
            AITLibrary.MediaManagementService.UpdateMediaRequest inValue = new AITLibrary.MediaManagementService.UpdateMediaRequest();
            inValue.Body = new AITLibrary.MediaManagementService.UpdateMediaRequestBody();
            inValue.Body.media = media;
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).UpdateMediaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.BorrowListsResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.BorrowLists(AITLibrary.MediaManagementService.BorrowListsRequest request) {
            return base.Channel.BorrowLists(request);
        }
        
        public AITLibrary.MediaManagementService.WBorrowDTO[] BorrowLists() {
            AITLibrary.MediaManagementService.BorrowListsRequest inValue = new AITLibrary.MediaManagementService.BorrowListsRequest();
            inValue.Body = new AITLibrary.MediaManagementService.BorrowListsRequestBody();
            AITLibrary.MediaManagementService.BorrowListsResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).BorrowLists(inValue);
            return retVal.Body.BorrowListsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.BorrowListsResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.BorrowListsAsync(AITLibrary.MediaManagementService.BorrowListsRequest request) {
            return base.Channel.BorrowListsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.BorrowListsResponse> BorrowListsAsync() {
            AITLibrary.MediaManagementService.BorrowListsRequest inValue = new AITLibrary.MediaManagementService.BorrowListsRequest();
            inValue.Body = new AITLibrary.MediaManagementService.BorrowListsRequestBody();
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).BorrowListsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AITLibrary.MediaManagementService.ReserveListResponse AITLibrary.MediaManagementService.MediaManagementServiceSoap.ReserveList(AITLibrary.MediaManagementService.ReserveListRequest request) {
            return base.Channel.ReserveList(request);
        }
        
        public AITLibrary.MediaManagementService.WReservationsDTO[] ReserveList() {
            AITLibrary.MediaManagementService.ReserveListRequest inValue = new AITLibrary.MediaManagementService.ReserveListRequest();
            inValue.Body = new AITLibrary.MediaManagementService.ReserveListRequestBody();
            AITLibrary.MediaManagementService.ReserveListResponse retVal = ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).ReserveList(inValue);
            return retVal.Body.ReserveListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AITLibrary.MediaManagementService.ReserveListResponse> AITLibrary.MediaManagementService.MediaManagementServiceSoap.ReserveListAsync(AITLibrary.MediaManagementService.ReserveListRequest request) {
            return base.Channel.ReserveListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AITLibrary.MediaManagementService.ReserveListResponse> ReserveListAsync() {
            AITLibrary.MediaManagementService.ReserveListRequest inValue = new AITLibrary.MediaManagementService.ReserveListRequest();
            inValue.Body = new AITLibrary.MediaManagementService.ReserveListRequestBody();
            return ((AITLibrary.MediaManagementService.MediaManagementServiceSoap)(this)).ReserveListAsync(inValue);
        }
    }
}
